topology: fix support for disabled MD5 authentication
net-snmp can be built with disabled MD5 authentication which causes a build
failure in eth-ff:
hpnmgt_snmp.c:2142:40: error: 'usmHMACMD5AuthProtocol' undeclared (first use in this function); did you mean 'usmHMACSHA1AuthProtocol'?
 2142 |                         authProtocol = usmHMACMD5AuthProtocol;
      |                                        ^~~~~~~~~~~~~~~~~~~~~~
      |                                        usmHMACSHA1AuthProtocol
hpnmgt_snmp.c:2142:40: note: each undeclared identifier is reported only once for each function it appears in

Use the NETSNMP_DISABLE_MD5 flag to detect this use case and output a comprehensible error to user.

Signed-off-by: Nicolas Morey <nmorey@suse.com>